version: "3.9"
services:

  prueba-linktic-ecommerce:
    image: prueba-linktic-ecommerce
    container_name: linktic-ecommerce-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9000"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: ecommerce_database
    environment:
      MYSQL_ROOT_PASSWORD: 1998
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: sosorio
      MYSQL_PASSWORD: 150919
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume: